# Generated by Django 3.1.5 on 2021-06-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_alter_post_postid'),
    ]

    operations = [
        migrations.CreateModel(
            name='userDetails',
            fields=[
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('rating', models.FloatField(null=True)),
                ('institute', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('pPhoto', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('links', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
