# Generated by Django 3.2.4 on 2021-06-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210623_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pPhoto',
            field=models.ImageField(blank=True, default='users/images/default.png', upload_to='users/images'),
        ),
    ]
