# Generated by Django 3.2.4 on 2021-06-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210623_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='pPhoto',
            field=models.ImageField(default='users/images/default.png', upload_to='users/images'),
        ),
    ]
